<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 800; letter-spacing: -0.02em;">
        Exploración y Diagnóstico Inicial de Datos 🔎
      </h1>
      <p style="margin: 6px 0 0 0; color: #1e3a8a; font-size: 1.15em; font-weight: 600; font-family: system-ui, -apple-system, sans-serif;">
        Especialización en Ciencia de Datos | Programación para Ciencia de Datos
      </p>
      <p style="margin: 4px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Universidad Santo Tomás — Seccional Tunja
      </p>
    </td>
    <td style="text-align: right; vertical-align: middle; border: none; padding: 15px 20px; width: 30%;">
      <span style="background: #1e3a8a; color: #ffffff; padding: 6px 14px; border-radius: 20px; font-size: 0.85em; font-weight: 700; display: inline-block; margin-bottom: 8px;">
        Módulo 03
      </span><br>
      <span style="color: #64748b; font-size: 0.85em;">Docente: Santiago A. Zúñiga M.</span><br>
      <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; font-size: 0.8em; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
    </td>
  </tr>
</table>

---
## Exploración de Datos 

Una vez que importamos nuestro dataset, el siguiente paso natural es explorarlo para entender qué información contiene, cómo está estructurada y si hay datos faltantes. 

Pandas ofrece numerosos atributos y funciones para obtener rápidamente una vista panorámica (metadata) de nuestros DataFrames.

In [1]:
import os
import urllib.parse
import urllib.request
import pandas as pd

# 🚀 Función de utilidad para cargar datasets de forma segura (Local o Google Colab)
def load_dataset(filename, module_name="03 - Pandas"):
    candidates = [
        f"data/{filename}",
        f"{module_name}/data/{filename}",
        filename
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
            
    os.makedirs("data", exist_ok=True)
    target_path = f"data/{filename}"
    encoded_module = urllib.parse.quote(module_name)
    encoded_file = urllib.parse.quote(filename)
    url_main = f"https://raw.githubusercontent.com/sazuniga06/Data-Science-Programming---USTA-Tunja-Repository/main/{encoded_module}/data/{encoded_file}"
    url_master = f"https://raw.githubusercontent.com/sazuniga06/Data-Science-Programming---USTA-Tunja-Repository/master/{encoded_module}/data/{encoded_file}"
    
    print(f"📥 Descargando dataset '{filename}' desde el repositorio oficial...")
    try:
        urllib.request.urlretrieve(url_main, target_path)
    except Exception:
        urllib.request.urlretrieve(url_master, target_path)
    print(f"✅ Dataset '{filename}' cargado exitosamente.")
    return target_path

# Carga del dataset desde ruta local o descarga automática desde GitHub
file_path = load_dataset('winemag-data-130k-v2.csv', '03 - Pandas')
reviews = pd.read_csv(file_path, index_col=0)
reviews.head(3)

---
### 1. Atributos y metadatos base 🏷️

Los objetos de pandas tienen varios atributos (variables internas que no llevan paréntesis al final) que nos permiten acceder a su información estructural:

- `shape`: devuelve una tupla con las dimensiones del objeto (filas, columnas), de manera idéntica a los *ndarrays* de NumPy.
- Etiquetas de los ejes:
  - **Series:** `index` (es su único eje)
  - **DataFrame:** `index` (para las filas) y `columns` (para las columnas)
  
🤓 *Nota: ¡Estos atributos pueden ser asignados/modificados de forma segura!*

In [2]:
print("Dimensiones (filas, columnas):", wine_reviews.shape)

display(wine_reviews.index)
display(wine_reviews.columns)

Dimensiones (filas, columnas): (129971, 13)
RangeIndex(start=0, stop=129971, step=1)
Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='str')

Por ejemplo, podemos aprovechar que las columnas son modificables para reescribir todos los nombres en mayúsculas usando una comprensión de listas (*List Comprehension*) de Python:

In [3]:
# Reescribimos los nombres de las columnas en mayúsculas
wine_reviews.columns = [x.upper() for x in wine_reviews.columns]
display(wine_reviews.columns)

Index(['COUNTRY', 'DESCRIPTION', 'DESIGNATION', 'POINTS', 'PRICE', 'PROVINCE',
       'REGION_1', 'REGION_2', 'TASTER_NAME', 'TASTER_TWITTER_HANDLE', 'TITLE',
       'VARIETY', 'WINERY'],
      dtype='str')

---
##### 🛠️ Práctica 1: Normalización de columnas

Escribir columnas en mayúsculas puede ser un poco agresivo a la vista. 
Cambia el atributo `columns` del DataFrame `wine_reviews` nuevamente, esta vez para que todos los nombres estén en minúsculas (puedes usar el método `.lower()` de los strings de Python).

In [ ]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución guiada...</b></summary>

```python
wine_reviews.columns = [x.lower() for x in wine_reviews.columns]
display(wine_reviews.columns)
```
</details>

---
### 2. Visualizando los datos (Head, Tail, Info) 👀

Para visualizar una pequeña muestra de un objeto Series o DataFrame y no colapsar la pantalla, usamos los métodos `head()` y `tail()`. El número predeterminado de elementos a mostrar es cinco, pero puedes pasarle un número personalizado.

In [4]:
# Primeras 5 filas (por defecto)
wine_reviews.head()

    COUNTRY                                                                                                                                                                                                                                                DESCRIPTION                         DESIGNATION  POINTS  PRICE           PROVINCE  ...           REGION_2         TASTER_NAME TASTER_TWITTER_HANDLE                                                                                TITLE         VARIETY               WINERY
0     Italy                                                                               Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.                        Vulkà Bianco      87    NaN  Sicily & Sardinia  ...                NaN       Kerin O’Keefe          @kerinokeefe                                                    Nicosia 2013 Vulkà Bianco  (Etna)     White Blend              Nicosia
1  Portugal                        This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.                            Avidagos      87   15.0              Douro  ...                NaN          Roger Voss            @vossroger                                        Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  Quinta dos Avidagos
2        US                                                                 Tart and snappy, the flavors of lime flesh and rind dominate. Some green pineapple pokes through, with crisp acidity underscoring the flavors. The wine was all stainless-steel fermented.                                 NaN      87   14.0             Oregon  ...  Willamette Valley        Paul Gregutt           @paulgwine                                         Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris            Rainstorm
3        US                                                    Pineapple rind, lemon pith and orange blossom start off the aromas. The palate is a bit more opulent, with notes of honey-drizzled guava and mango giving way to a slightly astringent, semidry finish.                Reserve Late Harvest      87   13.0           Michigan  ...                NaN  Alexander Peartree                   NaN                  St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)        Riesling           St. Julian
4        US  Much like the regular bottling from 2012, this comes across as rather rough and tannic, with rustic, earthy, herbal characteristics. Nonetheless, if you think of it as a pleasantly unfussy country wine, it's a good companion to a hearty winter stew.  Vintner's Reserve Wild Child Block      87   65.0             Oregon  ...  Willamette Valley        Paul Gregutt           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)      Pinot Noir         Sweet Cheeks

In [5]:
# Últimas 2 filas
wine_reviews.tail(2)

       COUNTRY                                                                                                                                                                                                               DESCRIPTION                    DESIGNATION  POINTS  PRICE PROVINCE  ... REGION_2 TASTER_NAME TASTER_TWITTER_HANDLE                                                                        TITLE         VARIETY                WINERY
129969  France  A dry style of Pinot Gris, this is crisp with some acidity. It also has weight and a solid, powerful core of spice and baked apple flavors. With its structure still developing, the wine needs to age. Drink from 2015.                            NaN      90   32.0   Alsace  ...      NaN  Roger Voss            @vossroger                                Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris  Domaine Marcel Deiss
129970  France                                                 Big, rich and off-dry, this is powered by intense spiciness and rounded texture. Lychees dominate the fruit profile, giving an opulent feel to the aftertaste. Drink now.  Lieu-dit Harth Cuvée Caroline      90   21.0   Alsace  ...      NaN  Roger Voss            @vossroger  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)  Gewürztraminer      Domaine Schoffit

El método `info()` nos brinda toda la información técnica clave sobre el DataFrame de un solo vistazo: cantidad de registros, conteo de valores nulos, y el tipo de dato subyacente en memoria de cada columna.

In [6]:
wine_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   COUNTRY                129908 non-null  str
 1   DESCRIPTION            129971 non-null  str
 2   DESIGNATION            92506 non-null   str
 3   POINTS                 129971 non-null  int64
 4   PRICE                  120975 non-null  float64
 5   PROVINCE               129908 non-null  str
 6   REGION_1               108724 non-null  str
 7   REGION_2               50511 non-null   str
 8   TASTER_NAME            103727 non-null  str
 9   TASTER_TWITTER_HANDLE  98758 non-null   str
 10  TITLE                  129971 non-null  str
 11  VARIETY                129970 non-null  str
 12  WINERY                 129971 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 12.9 MB

---
### 3. Resumen estadístico (`describe`) 📊

El método `describe()` muestra un resumen estadístico rápido de tus datos. Es "inteligente" respecto al tipo de dato (`type-aware`), lo que significa que su salida cambia según si los datos son numéricos o categóricos.

In [7]:
# Si no le pasamos argumentos, por defecto describe SÓLO las columnas numéricas
wine_reviews.describe()

          POINTS      PRICE
count  129971.00  120975.00
mean       88.45      35.36
std         3.04      41.02
min        80.00       4.00
25%        86.00      17.00
50%        88.00      25.00
75%        91.00      42.00
max       100.00    3300.00

Para datos tipo `object` (como textos o strings), el resumen incluirá el conteo (`count`), los valores únicos (`unique`), el valor más común (`top`) y la frecuencia de ese valor más común (`freq`).

Podemos forzarlo a describir TODAS las columnas:

In [8]:
# Describe todas las columnas (las numéricas tendrán valores nulos en top/freq)
wine_reviews.describe(include='all')

       COUNTRY                                                                                                                                                                                                                DESCRIPTION DESIGNATION     POINTS      PRICE    PROVINCE  ...       REGION_2 TASTER_NAME TASTER_TWITTER_HANDLE                                                   TITLE     VARIETY              WINERY
count   129908                                                                                                                                                                                                                     129971       92506  129971.00  120975.00      129908  ...          50511      103727                 98758                                                  129971      129970              129971
unique      43                                                                                                                                                                                                                     119955       37979        NaN        NaN         425  ...             17          19                    15                                                  118840         707               16757
top         US  This zesty red has pretty aromas that suggest small red berry, blue flower and a whiff of moist soil. The vibrant palate offers sour cherry, pomegranate and a hint of anise alongside zesty acidity and refined tannins.     Reserve        NaN        NaN  California  ...  Central Coast  Roger Voss            @vossroger  Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma County)  Pinot Noir  Wines & Winemakers
freq     54504                                                                                                                                                                                                                          3        2009        NaN        NaN       36247  ...          11065       25514                 25514                                                      11       13272                 222
mean       NaN                                                                                                                                                                                                                        NaN         NaN      88.45      35.36         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN
...        ...                                                                                                                                                                                                                        ...         ...        ...        ...         ...  ...            ...         ...                   ...                                                     ...         ...                 ...
min        NaN                                                                                                                                                                                                                        NaN         NaN      80.00       4.00         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN
25%        NaN                                                                                                                                                                                                                        NaN         NaN      86.00      17.00         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN
50%        NaN                                                                                                                                                                                                                        NaN         NaN      88.00      25.00         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN
75%        NaN                                                                                                                                                                                                                        NaN         NaN      91.00      42.00         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN
max        NaN                                                                                                                                                                                                                        NaN         NaN     100.00    3300.00         NaN  ...            NaN         NaN                   NaN                                                     NaN         NaN                 NaN

También puedes apuntar `describe()` a una columna específica (una Series) para ver su resumen individual:

In [9]:
# Aseguramos columnas en minúsculas para consistencia
wine_reviews.columns = wine_reviews.columns.str.lower()
wine_reviews["taster_name"].describe()

count         103727
unique            19
top       Roger Voss
freq           25514

---
### 4. Funciones estadísticas particulares 🧮

Si deseas obtener algún estadístico resumido particular, normalmente hay una función específica de Pandas que lo hace directamente.

Por ejemplo, para ver el **promedio** de los puntos otorgados, usamos `mean()`:

In [10]:
wine_reviews["points"].mean()

np.float64(88.44713820775404)

Para ver una lista de **valores únicos** (sin repeticiones) de una categoría, usamos `unique()`:

In [11]:
wine_reviews["taster_name"].unique()

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',                  nan,
   'Sean P. Sullivan',         'Jim Gordon',     'Joe Czerwinski',
   'Anne Krebiehl MW',      'Lauren Buzzeo',      'Mike DeSimone',
       'Jeff Jenssen',    'Susan Kostrzewa',       'Carrie Dykes',
        'Fiona Adams',  'Christina Pickard']
Length: 20, dtype: str

Para ver una lista de los valores únicos y **cuántas veces ocurren** en el dataset, usamos el maravilloso método `value_counts()`:

In [12]:
wine_reviews["taster_name"].value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
                      ...
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6

---
##### 🛠️ Práctica 2: Extracción de información estadística

Responde con código a las siguientes preguntas analíticas:
1. ¿Cuál es el precio **máximo** registrado en este conjunto de reseñas? *(Pista: hay una función `max()`)*
2. ¿Cuántos **países** diferentes hay en la base de datos y cuáles son? *(Pista: fíjate en la columna `'country'` y en la función `unique()` o `nunique()`)*
3. Haz un **conteo** de vinos reseñados por provincia (`'province'`).

In [ ]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución guiada...</b></summary>

```python
# 1. Precio Máximo
precio_max = wine_reviews["price"].max()
print("Precio máximo registrado:", precio_max)

# 2. Países únicos
paises = wine_reviews["country"].unique()
print("\nPaíses diferentes:", len(paises)) # o wine_reviews['country'].nunique()
print(paises)

# 3. Conteo por provincia
display(wine_reviews["province"].value_counts())
```
</details>

---
<div align="center">
  <p style="font-size: 0.9em; color: #64748b;">
    © 2026 <b>Universidad Santo Tomás — Seccional Tunja</b><br>
    <i>Especialización en Ciencia de Datos | Programación para Ciencia de Datos</i>
  </p>
</div>