<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Indexación y Selección de Datos
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Indexación y Selección de Datos 

Seleccionar columnas o filas específicas de un DataFrame es una de las tareas más comunes e importantes en la manipulación de datos. Pandas nos ofrece múltiples formas de extraer exactamente la porción de datos que necesitamos.

In [1]:
# Configuramos la salida múltiple y cargamos los datos
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd

wine_reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)

---
### 1. Acceso a Columnas (Atributos vs Corchetes)

#### 1.1 Acceso como Atributo (Punto)
Puedes acceder a una columna de un DataFrame directamente como si fuera un atributo utilizando el punto (`.`). Por ejemplo, para acceder a la propiedad `country` de nuestro DataFrame:

In [2]:
wine_reviews.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

⚠️ **¡Advertencia importante!**
Solo puedes utilizar este tipo de acceso si el nombre de la columna es un identificador de Python **válido**. Por ejemplo:
- No puedes usar números (`wine_reviews.1` no es válido).
- No puedes usar nombres con espacios (`wine_reviews.taster name`).
- No funcionará si el nombre de la columna entra en conflicto con un método existente de Pandas (por ejemplo, si tienes una columna llamada `min`, `wine_reviews.min` ejecutará la función mínima, no te devolverá la columna).

#### 1.2 Acceso con Corchetes `[]` (Getitem)
La forma estándar, más segura y común de indexar columnas es utilizando corchetes (`[]`). Si pasas un solo nombre, te devolverá una `Series`.

In [3]:
display(wine_reviews['country'])
print("Tipo:", type(wine_reviews['country']))

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

Tipo: <class 'pandas.core.series.Series'>

Para extraer un valor único, usamos el operador de indexación dos veces (primero la columna, luego la fila):

In [4]:
wine_reviews['country'][0]

'Italy'

También puedes pasar una **lista de columnas** dentro de los corchetes `[['col1', 'col2']]` para seleccionar múltiples columnas al mismo tiempo. En este caso, Pandas devolverá un `DataFrame`, no una Series:

In [5]:
display(wine_reviews[['country', 'price']])
print("Tipo:", type(wine_reviews[['country', 'price']]))

         country  price
0          Italy    NaN
1       Portugal   15.0
2             US   14.0
3             US   13.0
4             US   65.0
...          ...    ...
129966   Germany   28.0
129967        US   75.0
129968    France   30.0
129969    France   32.0
129970    France   21.0

[129971 rows x 2 columns]

Tipo: <class 'pandas.core.frame.DataFrame'>

---
### 2. Rangos de corte (Slicing `[:]`) ✂️

Con las **Series**, la sintaxis del rebanado (*slicing*) funciona exactamente igual que con una lista de Python o un arreglo de NumPy, devolviendo un corte de los valores y sus etiquetas correspondientes.

In [6]:
# Haciendo slicing a una Series (columna country)
wine_reviews['country'][3:9]

3         US
4         US
5      Spain
6      Italy
7     France
8    Germany
Name: country, dtype: object

Con un **DataFrame**, al hacer slicing directamente dentro de los corchetes `[]`, Pandas corta las **filas**. Esto se diseñó así por simple conveniencia, ya que es una operación muy común.

In [7]:
# Haciendo slicing directamente al DataFrame entero (corta filas)
wine_reviews[3:9]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

---
### 3. Selección experta con `loc` e `iloc` 🗺️

¿Cómo hacemos para seleccionar **filas Y columnas específicas** al mismo tiempo? Usar solo los corchetes `[]` no es suficiente para cortes precisos de dos dimensiones. Para esto, existen los operadores `loc` e `iloc`.

La sintaxis siempre es: `dataframe.iloc[filas_que_quieres, columnas_que_quieres]`

#### 3.1 Selección por Posición (`iloc`)
`iloc` viene de *Integer Location*. Permite hacer selecciones basadas puramente en los **índices numéricos de las posiciones**, ignorando el nombre de las columnas. Sigue la regla tradicional de Python (el límite inferior se incluye, el superior no).

In [8]:
# Extraer la primera fila entera (posición 0)
wine_reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [9]:
# Extraer TODAS las filas (:), pero solo de la primera columna (posición 0)
wine_reviews.iloc[:, 0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [10]:
# Seleccionar las tres primeras filas, de la primera columna
wine_reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [11]:
# También podemos pasarle listas arbitrarias
wine_reviews.iloc[[0, 1, 10, 100], 0]

0         Italy
1      Portugal
10           US
100          US
Name: country, dtype: object

#### 3.2 Selección por Etiqueta (`loc`)
`loc` viene de *Location*. Permite hacer selecciones puramente basadas en el **nombre (etiqueta)** de las filas y las columnas.

⚠️ **Cuidado con `loc`**: Contrario al corte habitual de Python, en `loc` el límite final **SÍ se incluye**.

In [12]:
# Para obtener la primera entrada (etiquetada como '0') de la columna con etiqueta 'country'
wine_reviews.loc[0, 'country']

'Italy'

In [13]:
# Extraer todas las filas de una lista específica de nombres de columnas
wine_reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

               taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

**Transición entre loc e iloc (Combinación):**
¿Qué pasa si deseas obtener los elementos 0 y 2 del índice pero utilizando la etiqueta de columna 'country'?
Puedes apoyarte en la función `get_loc` de las columnas, o usar los índices directamente sobre `loc`.

In [14]:
display(wine_reviews.loc[wine_reviews.index[[0, 2]], 'country'])

# O combinando con iloc pidiendo que busque la posición de la palabra 'country'
posicion_country = wine_reviews.columns.get_loc('country')
display(wine_reviews.iloc[[0, 2], posicion_country])

0    Italy
2       US
Name: country, dtype: object

0    Italy
2       US
Name: country, dtype: object

---
##### 🛠️ Práctica 1: Jugando con loc e iloc

Utiliza la herramienta adecuada (`loc` o `iloc`) para:
1. Seleccionar las filas de la posición 10 a la posición 15.
2. Seleccionar, para esas mismas filas, **solo** las columnas `title` y `price`.
Guarda el resultado en una variable llamada `subset_vinos` e imprímelo.

In [15]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
subset_vinos = wine_reviews.loc[10:15, ['title', 'price']]
display(subset_vinos)
```
</details>

---
### 4. Indexación Booleana (Condicional) 🎭

Hasta ahora hemos extraído fragmentos utilizando propiedades estructurales del DataFrame. Sin embargo, para hacer cosas interesantes con los datos, solemos necesitar **hacer preguntas basadas en condiciones** (filtros).

Por ejemplo, supongamos que estamos interesados ​​específicamente en los vinos producidos en Italia.
Podemos comenzar preguntándole al DataFrame: ¿Eres de Italia o no?

In [16]:
# Esto devuelve una "Máscara Booleana" (una serie llena de True / False)
wine_reviews['country'] == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

Ahora, simplemente inyectamos esa Máscara Booleana dentro de nuestro poderoso `loc` para que filtre y traiga solo las filas que son `True`:

In [17]:
wine_reviews.loc[wine_reviews['country'] == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

**Múltiples condiciones (AND `&` y OR `|`)**

Queríamos saber cuáles vinos italianos son mejores que el promedio. Sabiendo que los vinos se puntúan en una escala hasta 100, queremos vinos que tengan al menos 90 puntos.

Podemos utilizar el *ampersand* (`&`) para indicar que se deben cumplir **ambas** condiciones a la vez (AND). **Nota vital:** Siempre debes colocar paréntesis `()` alrededor de cada condición independiente.

In [18]:
# Vinos de Italia que TAMBIÉN tienen 90 o más puntos
wine_reviews.loc[(wine_reviews['country'] == 'Italy') & (wine_reviews['points'] >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

Supongamos que en cambio compraremos cualquier vino que se haga en Italia **O** que tenga más de 90 puntos sin importar el país. Para el condicional OR usamos la barra vertical (`|`):

In [19]:
# Vinos de Italia O que tengan 90 o más puntos
wine_reviews.loc[(wine_reviews['country'] == 'Italy') | (wine_reviews['points'] >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

---
### 5. Métodos `isin()` y `notnull()`

Pandas incluye funciones diseñadas para ahorrarnos escribir filtros booleanos interminables.

- **`isin(lista)`**: Retorna `True` si el valor de la fila coincide con **cualquiera** de los elementos de la lista que le pases. Muy útil para buscar múltiples categorías sin llenar todo de condiciones `|`.

In [20]:
# Filtrar vinos que sean de Italia o de Francia
wine_reviews.loc[wine_reviews['country'].isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

- **`notnull()`** y su reverso **`isnull()`**: Te permiten resaltar valores que están (o no están) vacíos/Nulos (NaN). Por ejemplo, si quisiéramos filtrar todos los vinos que no tengan una etiqueta de precio (`price` no nulo):

In [21]:
wine_reviews.loc[wine_reviews['price'].notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

---
##### 🛠️ Práctica 2: Filtros Booleanos Avanzados

Utiliza Máscaras Booleanas dentro de `loc` para resolver este desafío:
- Queremos filtrar todos los vinos cuyo **país** sea España (`'Spain'`) y que su **precio** sea estrictamente menor a 15 (`< 15`).
- Asigna los resultados a una variable llamada `ofertas_españolas` e imprime las primeras 5 filas con `head()`.

In [22]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
ofertas_españolas = wine_reviews.loc[(wine_reviews['country'] == 'Spain') & (wine_reviews['price'] < 15)]
display(ofertas_españolas.head())
```
</details>