<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Añadir y Eliminar Columnas
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Añadir y Eliminar Columnas 

Conceptualmente, puedes tratar un DataFrame como si fuera un diccionario (`dict`) de objetos Series que comparten el mismo índice. 

Por lo tanto, obtener, asignar y eliminar columnas funciona con una sintaxis prácticamente idéntica a las operaciones de diccionarios en Python nativo.

Para explorar esto, construiremos un pequeño DataFrame de ciudades:

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd

cities = pd.DataFrame(
    [
        ['California', 39512223, 423967, 'West'],
        ['Washington', 7614893, 184661, 'West'],
        ['New York', 19453561, 141297, 'Est'],
        ['North Carolina', 10488084, 139391, 'Est'],
        ['Florida', 21477737, 170312, 'Est']
    ],
    columns=['name', 'population', 'area', 'position']
)
display(cities)

             name  population    area position
0      California    39512223  423967     West
1      Washington     7614893  184661     West
2        New York    19453561  141297      Est
3  North Carolina    10488084  139391      Est
4         Florida    21477737  170312      Est

---
### 1. Añadir Columnas

La forma más básica de añadir una columna es asignarle valores a una nueva llave del DataFrame. De forma predeterminada, **las nuevas columnas se insertan al final (a la derecha).**

In [2]:
# Convertimos la población a millones
cities['population (M)'] = cities['population'] / 1000000
display(cities)

             name  population    area position  population (M)
0      California    39512223  423967     West       39.512223
1      Washington     7614893  184661     West        7.614893
2        New York    19453561  141297      Est       19.453561
3  North Carolina    10488084  139391      Est       10.488084
4         Florida    21477737  170312      Est       21.477737

También podemos crear columnas lógicas booleanas directamente evaluando condiciones (creará valores `True` o `False`):

In [3]:
cities['high-density'] = (cities['population'] / cities['area']) > 100.0
display(cities)

             name  population    area position  population (M)  high-density
0      California    39512223  423967     West       39.512223         False
1      Washington     7614893  184661     West        7.614893         False
2        New York    19453561  141297      Est       19.453561          True
3  North Carolina    10488084  139391      Est       10.488084         False
4         Florida    21477737  170312      Est       21.477737          True

#### Insertar en una posición específica (`insert`)
Si no quieres que la columna vaya al final, el método `insert()` te permite colocarla exactamente donde quieres (usando el índice numérico de la posición de la columna).

In [4]:
pop_density = cities['population'] / cities['area']

# Insertamos en la posición 3 (es decir, como la 4ta columna)
cities.insert(3, "population density", pop_density)
display(cities)

,name,population,area,population density,position,population (M),high-density
0,California,39512223,423967,93.196459,West,39.512223,False
1,Washington,7614893,184661,41.237148,West,7.614893,False
2,New York,19453561,141297,137.678514,Est,19.453561,True
3,North Carolina,10488084,139391,75.242189,Est,10.488084,False
4,Florida,21477737,170312,126.108184,Est,21.477737,True

---
### 2. Eliminar Columnas (`drop`)

Para eliminar usamos la función `drop()`. Es de suma importancia especificar el argumento `axis=1`, lo que le indica a Pandas que estamos buscando en las columnas, no en las filas (`axis=0`).

In [5]:
cities.drop('population (M)', axis=1)

,name,population,area,population density,position,high-density
0,California,39512223,423967,93.196459,West,False
1,Washington,7614893,184661,41.237148,West,False
2,New York,19453561,141297,137.678514,Est,True
3,North Carolina,10488084,139391,75.242189,Est,False
4,Florida,21477737,170312,126.108184,Est,True

⚠️ **¡Cuidado! El DataFrame original no ha sido modificado aún.**
Casi todas las funciones destructivas en Pandas devuelven una *copia* visual del DataFrame con el cambio aplicado, pero dejan el original intacto por seguridad.

In [6]:
display(cities)

,name,population,area,population density,position,population (M),high-density
0,California,39512223,423967,93.196459,West,39.512223,False
1,Washington,7614893,184661,41.237148,West,7.614893,False
2,New York,19453561,141297,137.678514,Est,19.453561,True
3,North Carolina,10488084,139391,75.242189,Est,10.488084,False
4,Florida,21477737,170312,126.108184,Est,21.477737,True

Si de verdad queremos hacer el borrado permanente, tenemos dos opciones válidas:

**Solución 1) Reasignar la variable:** Sobrescribimos el DataFrame.

In [7]:
cities = cities.drop('population (M)', axis=1)
display(cities)

,name,population,area,population density,position,high-density
0,California,39512223,423967,93.196459,West,False
1,Washington,7614893,184661,41.237148,West,False
2,New York,19453561,141297,137.678514,Est,True
3,North Carolina,10488084,139391,75.242189,Est,False
4,Florida,21477737,170312,126.108184,Est,True

**Solución 2) Usar el parámetro `inplace=True`:** Esto fuerza a Pandas a mutar el DataFrame original sin devolver copias. Es un poco más rápido y gasta menos memoria RAM.

In [8]:
cities.drop('population density', axis=1, inplace=True)
display(cities)

             name  population    area position  high-density
0      California    39512223  423967     West         False
1      Washington     7614893  184661     West         False
2        New York    19453561  141297      Est          True
3  North Carolina    10488084  139391      Est         False
4         Florida    21477737  170312      Est          True

---
##### 🛠️ Práctica: Limpieza de Columnas
Elimina la columna `position` del DataFrame `cities` de manera permanente utilizando el parámetro `inplace=True`.

In [9]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
cities.drop('position', axis=1, inplace=True)
display(cities)
```
</details>