<table style="width: 100%; border-collapse: collapse; border: none; background: #f8fafc; border-left: 6px solid #1e3a8a; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
  <tr style="border: none;">
    <td style="vertical-align: middle; border: none; padding: 15px 20px;">
      <h1 style="margin: 0; color: #0f172a; font-size: 2.1em; font-family: system-ui, -apple-system, sans-serif; font-weight: 700; line-height: 1.2;">
        Exploración Preliminar
      </h1>
      <p style="margin: 6px 0 0 0; color: #64748b; font-size: 0.95em; font-family: system-ui, -apple-system, sans-serif;">
        Programación para Ciencia de Datos
      </p>
    </td>
    <td style="vertical-align: middle; text-align: right; border: none; padding: 15px 20px; min-width: 240px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="font-size: 0.9em; color: #334155; line-height: 1.5;">
        <strong style="color: #1e3a8a; font-size: 1em;">Especialización en Ciencia de Datos</strong><br>
        <span style="color: #475569; font-weight: 600;">USTA Tunja</span><br><br>
        <b>Santiago A. Zúñiga M.</b><br>
        ✉️ <a href="mailto:gestorvirtualcienciadatos@ustatunja.edu.co" style="color: #2563eb; text-decoration: none; font-weight: 500;">gestorvirtualcienciadatos@ustatunja.edu.co</a>
      </div>
    </td>
  </tr>
</table>

---
## Carga de Datos y Exploración Inicial 🕵️‍♂️

Para explorar el valor real del Análisis Exploratorio de Datos, utilizaremos un archivo llamado `quartets.csv`. Este archivo contiene 4 conjuntos de datos diminutos que nos ayudarán a entender rápidamente el inmenso valor de graficar y explorar nuestra información.

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd

# Cargamos el dataset
quartets = pd.read_csv('data/quartets.csv', index_col=0)

### Exploración Preliminar
Lo primero que siempre debemos hacer al cargar un nuevo dataset es mirar su información técnica básica usando `.info()`.

In [2]:
quartets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 1 to 11
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   x        44 non-null     int64
 1   y        44 non-null     float64
 2   quartet  44 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.4+ KB

Vemos que hay **44 entradas (filas)**, dos columnas numéricas (`x` e `y`) y una columna de tipo objeto (texto) llamada `quartet` que potencialmente identifica a cada uno de los 4 conjuntos de datos.

¿Cómo se ve físicamente este DataFrame? Utilicemos `.head()` para ver las primeras filas y `.sample()` para tomar una muestra aleatoria.

In [3]:
# Primeras 5 filas
quartets.head()

    x     y quartet
1  10  8.04       I
2   8  6.95       I
3  13  7.58       I
4   9  8.81       I
5  11  8.33       I

In [4]:
# 5 filas aleatorias (muy útil para no sesgarnos solo con el inicio de la tabla)
quartets.sample(5)

     x      y quartet
5   11   9.26      II
8   19  12.50      IV
3   13   7.58       I
6   14   8.84     III
10   7   4.82       I

¿Cuáles son exactamente los nombres únicos de esos 4 conjuntos de datos que están en la columna `quartet`?

In [5]:
quartets['quartet'].unique().tolist()

['I', 'II', 'III', 'IV']

Para hacernos una mejor idea, podemos combinar `.groupby()` con funciones de exploración para ver fragmentos de cada uno de los 4 grupos al mismo tiempo:

In [6]:
# Mostrar las primeras 3 muestras de CADA grupo (cuarteto)
quartets.groupby('quartet').head(3)

    x      y quartet
1  10   8.04       I
2   8   6.95       I
3  13   7.58       I
1  10   9.14      II
2   8   8.14      II
3  13   8.74      II
1  10   7.46     III
2   8   6.77     III
3  13  12.74     III
1   8   6.58      IV
2   8   5.76      IV
3   8   7.71      IV

In [7]:
# Mostrar 2 muestras ALEATORIAS de CADA grupo
quartets.groupby('quartet').sample(2)

     x     y quartet
8    4  4.26       I
5   11  8.33       I
10   7  7.26      II
11   5  4.74      II
1   10  7.46     III
7    6  6.08     III
10   8  7.91      IV
11   8  6.89      IV

Finalmente, verifiquemos si los 4 conjuntos de datos están balanceados (tienen la misma cantidad de filas):

In [8]:
quartets.groupby('quartet').size()

quartet
I      11
II     11
III    11
IV     11
dtype: int64

---
##### 🛠️ Práctica: Explorando tus propios recortes
Imprime las **últimas 2 filas** de **cada grupo** utilizando la misma lógica de encadenamiento que vimos arriba.

In [9]:
# Escribe tu código aquí

<details>
<summary><b>💡 Haz clic aquí para ver la solución</b></summary>

```python
quartets.groupby('quartet').tail(2)
```
</details>